migcontrol/django-migcontrol

- requirements.txt
CC: @tchiliali - fixing an issue in compressor, it may have been the one that you ran into
> Downgrade django-comressor to fix current issue

- .pre-commit-config.yaml
Due to deprications in upstream services, we have to fix these two things.
> pre-commit configuration fixes

- blog/templates/blog/blog_page.html
- home/templates/home/home_page.html
- migcontrol/static/scss/content.scss
- migcontrol/templates/base.html
> Adds header images to blog posts

- migcontrol/static/scss/content.scss
> Adds border all-around blockquotes

- migcontrol/settings/base.py
Ability to view errors in server log
> Log exceptions to StreamHandler

- migcontrol/static/scss/nav.scss
> Change hover color in navbar to primary color

- locale/ar/LC_MESSAGES/django.po
- locale/de/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
- migcontrol/settings/base.py
Readies the first iteration of translations for layout elements
Fixes #46
> Add empty translation files

- migcontrol/templates/base.html
i have created a seardh icon under alignment2 branch
> Alignment2 and search icon

- .github/workflows/django.yml
This doesn't verify the translations themselves :) But it will check that the syntax is okay.
> Adds a Github action to test translations are okay

- .gitignore
- blog/models.py
> Fixes the Wagtail issue that got introduced in #70

- blog/templates/blog/index.html
> Remove Latest Updates

- blog/templates/blog/index.html
> Make the "read more" blog link in primary (red) color

- blog/models.py
- locale/ar/LC_MESSAGES/django.po
- locale/de/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
This was confusing for new translators
Fixes #89
> Remove some unnecessary translations

- blog/management/commands/wordpress_to_wagtail.py
Should only import username, since other fields are empty in source data.
> Fix bug in authors import

- migcontrol/static/scss/content.scss
> White text on primary button

- blog/management/commands/wordpress_to_wagtail.py
> Do not overwrite search_description if already set

- blog/management/commands/wordpress_to_wagtail.py
- wiki/models.py
> Insert wiki links in blog posts and wiki pages directly upon import

- blog/admin.py
- blog/models.py
- migcontrol/settings/base.py
> Adds a custom view for blog pages

- home/templates/bootstrap/button_panel.html
- home/templates/bootstrap/form.html
- home/templates/bootstrap/formerrors.html
- home/templates/bootstrap/formfield.html
- home/templatetags/bootstrap_tags.py
- library/forms.py
- library/models.py
- library/templates/library/index.html
- library/templates/library/media_page.html
- migcontrol/static/scss/content.scss
- migcontrol/static/scss/main.scss
- migcontrol/static/scss/sidebar.scss
> Adds filter for library index and general bootstrap styling for forms

- home/fields.py
- home/templates/home/blocks/carousel_blog.html
> Fixes the queryset that gets the latest blog post

- home/fields.py
- home/templates/home/blocks/section_card.html
> Adds a "read more" field for section cards

- .pre-commit-config.yaml
- locale/ar/LC_MESSAGES/django.po
- locale/de/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
> New translation sources

- blog/management/commands/wordpress_to_wagtail.py
- wiki/templates/wiki/wiki_page.html
Fixes https://github.com/migcontrol/django-migcontrol/issues/180
> Dont import authors but display them though!

- migcontrol/static/scss/content.scss
> Use default link style, add a top margin

- migcontrol/static/scss/content.scss
> Align section card height

- README.rst
- library/templates/library/index.html
- locale/ar/LC_MESSAGES/django.po
- locale/de/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
Fixes https://github.com/migcontrol/django-migcontrol/issues/197
> Replace "added" with "Year of Publication"

- library/templates/library/base.html
- library/templates/library/business/business_page.html
- library/templates/library/business/index.html
- library/templates/library/index.html
- library/templates/library/media_page.html
- migcontrol/templates/base.html
- migcontrol/templates/migcontrol/includes/submenu.html
> Add Monthly Review to library sub-menu

- library/templates/library/media_page.html
Fixes https://github.com/migcontrol/django-migcontrol/issues/216
> Fix broken external links

- locale/fr/LC_MESSAGES/django.po
CC @shavek these updates worked out fine, no so-called syntax errors or anything. Nice work by the translator :+1:
> French translation updates

- migcontrol/static/scss/main.scss
- migcontrol/static/scss/wiki.scss
- wiki/templates/wiki/index.html
Fixes https://github.com/migcontrol/django-migcontrol/issues/217
> Make wiki categories scrollable

- library/forms.py
- library/models.py
Fixes https://github.com/migcontrol/django-migcontrol/issues/213
> Remove media_type from search form, display all languages

- migcontrol/static/scss/content.scss
Fixes https://github.com/migcontrol/django-migcontrol/issues/172
> Make collaborators bold

- locale/ar/LC_MESSAGES/django.po
Refs https://github.com/migcontrol/django-migcontrol/issues/110
> Add Arabic translation

- library/forms.py
- library/templates/library/index.html
- library/templates/library/media_page.html
Fixes https://github.com/migcontrol/django-migcontrol/issues/214
Fixes https://github.com/migcontrol/django-migcontrol/issues/215
> Library index year

- library/forms.py
Fixes https://github.com/migcontrol/django-migcontrol/issues/229
> Add ability for free text search

- library/forms.py
> library search filter now displays Region and Topic in alphabetical order

- library/forms.py
checked library/forms.py with pre-commit
> pre-commit checked forms.py

- wiki/models.py
> Try out a specific collation for german

- migcontrol/static/scss/content.scss
> Add some missing margins

- library/templates/library/business/index.html
Adds text as mentioned in #274
> Render body blocks in Border Business index
